#pragma once

// DO NOT EDIT THIS FILE!
// This file is automatically generated. Changes to source should be made
// through relevant component source file.

/*
	olcPixelGameEngine3.h

	+-------------------------------------------------------------+
	|           OneLoneCoder Pixel Game Engine v3.00              |
	|  "What do you need? Pixels... Lots of Pixels..." - javidx9  |
	+-------------------------------------------------------------+

	What is this?
	~~~~~~~~~~~~~
	olc::PixelGameEngine is a single file, cross platform graphics and userinput
	framework used for games, visualisations, algorithm exploration and learning.
	It was developed by YouTuber "javidx9" as an assistive tool for many of his
	videos. The goal of this project is to provide high speed graphics with
	minimal project setup complexity, to encourage new programmers, younger people,
	and anyone else that wants to make fun things.

	However, olc::PixelGameEngine is not a toy! It is a powerful and fast utility
	capable of delivering high resolution, high speed, high quality applications
	which behave the same way regardless of the operating system or platform.

	This file provides the core utility set of the olc::PixelGameEngine, including
	window creation, keyboard/mouse input, main game thread, timing, pixel drawing
	routines, image/sprite loading and drawing routines, and a bunch of utility
	types to make rapid development of games/visualisations possible.


	License (OLC-3)
	~~~~~~~~~~~~~~~

	Copyright 2018 - 2025 OneLoneCoder.com

	Redistribution and use in source and binary forms, with or without modification,
	are permitted provided that the following conditions are met:

	1. Redistributions or derivations of source code must retain the above copyright
	notice, this list of conditions and the following disclaimer.

	2. Redistributions or derivative works in binary form must reproduce the above
	copyright notice. This list of conditions and the following	disclaimer must be
	reproduced in the documentation and/or other materials provided with the distribution.

	3. Neither the name of the copyright holder nor the names of its contributors may
	be used to endorse or promote products derived from this software without specific
	prior written permission.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS	"AS IS" AND ANY
	EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
	OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
	SHALL THE COPYRIGHT	HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
	INCIDENTAL,	SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
	TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
	BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
	CONTRACT, STRICT LIABILITY, OR TORT	(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
	ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
	SUCH DAMAGE.

	TLDR: 
	You can do whatever you want with this code. Your only obligation is to credit in a 
	visible way to your end users in your running program that you used this code or a 
	derivative of it. If you don't edit this file, you are automatically in compliance with
	OLC-3, as the message "OneLoneCoder.com" is present in the output window title bar. If
	you compile to full screen, or remove the title bar, then you must display somewhere
	something like "Powered by olcPixelGameEngine v3.00 - OneLoneCoder.com". That's it.

	Links
	~~~~~
	YouTube:	https://www.youtube.com/javidx9
				https://www.youtube.com/javidx9extra
	Discord:	https://discord.gg/WhwHUMV
	X:			https://www.x.com/javidx9
	Twitch:		https://www.twitch.tv/javidx9
	GitHub:		https://www.github.com/onelonecoder
	Homepage:	https://www.onelonecoder.com
	Patreon:	https://www.patreon.com/javidx9
*/


//! GRAB GLOBAL STDHEADER

//! GRAB config.h CONFIGURATION

//! GRAB pixel.h DECLARATION

//! GRAB vector2d.h DECLARATION

//! GRAB matrix3d.h DECLARATION

//! GRAB transform2d.h DECLARATION
 
//! GRAB image.h DECLARATION

//! GRAB font.h DECLARATION

//! GRAB imload_iface.h DECLARATION
 
//! GRAB gputask.h DECLARATION
 
//! GRAB gpu_iface.h DECLARATION

//! GRAB draw2d.h DECLARATION

//! GRAB hw_input.h	DECLARATION

//! GRAB hw_mouse.h	DECLARATION

//! GRAB window.h DECLARATION
 
//! GRAB host_iface.h DECLARATION

//! GRAB core.h	DECLARATION










#if OLC_HOST == OLC_HOST_WINDOWS
//! GRAB host_win_winapi.h WINAPI_CONFIG

//! GRAB host_win_winapi.h DECLARATION
#endif

#if OLC_HOST == OLC_HOST_MACOS
//! GRAB api_macos.h DECLARATION

//! GRAB api_macos_wrapper.hpp DECLARATION

//! GRAB host_apple_macos.h MACOS_CONFIG

//! GRAB host_apple_macos.h DECLARATION
#endif

#if OLC_GPU == OLC_GPU_OPENGL33
//! GRAB api_opengl.h OPENGL_CONFIG

//! GRAB api_opengl.h DECLARATION

//! GRAB gpu_opengl33.h DECLARATION
#endif

#if OLC_IMAGELOADER == OLC_IMAGELOADER_WINGDI
//! GRAB imload_wingdi.h WINAPI_CONFIG

//! GRAB imload_wingdi.h DECLARATION
#endif

#if OLC_IMAGELOADER == OLC_IMAGELOADER_MACOS
//! GRAB imload_macos.h DECLARATION
#endif








#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_HOST_IMPLEMENTED)
#if OLC_HOST == OLC_HOST_WINDOWS
//! GRAB host_win_winapi.cpp IMPLEMENTATION
#endif
#if OLC_HOST == OLC_HOST_MACOS
//! GRAB host_apple_macos.cpp IMPLEMENTATION

//! GRAB api_macos.cpp IMPLEMENTATION

#endif
#define PGE_HOST_IMPLEMENTED 1
#endif

#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_GPU_IMPLEMENTED)
#if OLC_GPU == OLC_GPU_OPENGL33
//! GRAB gpu_iface.cpp IMPLEMENTATION
//! GRAB api_opengl.cpp IMPLEMENTATION
//! GRAB gpu_opengl33.cpp IMPLEMENTATION
#endif
#define PGE_GPU_IMPLEMENTED 1
#endif

#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_DRAW2D_IMPLEMENTED)
//! GRAB draw2d.cpp IMPLEMENTATION 
#define PGE_DRAW2D_IMPLEMENTED 1
#endif

#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_CORE_IMPLEMENTED)
//! GRAB core.cpp IMPLEMENTATION 
#define PGE_CORE_IMPLEMENTED 1
#endif

#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_IMAGE_IMPLEMENTED)
//! GRAB image.cpp IMPLEMENTATION 
#define PGE_IMAGE_IMPLEMENTED 1
#endif

#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_FONT_IMPLEMENTED)
//! GRAB font.cpp IMPLEMENTATION 
#define PGE_FONT_IMPLEMENTED 1
#endif

#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_HW_MOUSE_IMPLEMENTED)
//! GRAB hw_mouse.cpp IMPLEMENTATION 
#define PGE_HW_MOUSE_IMPLEMENTED 1
#endif

#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_WINDOW_IMPLEMENTED)
//! GRAB window.cpp IMPLEMENTATION 
#define PGE_WINDOW_IMPLEMENTED 1
#endif

#if defined(OLC_PGE3_APPLICATION) && !defined(PGE_IMAGELOADER_IMPLEMENTED)
#if OLC_IMAGELOADER == OLC_IMAGELOADER_WINGDI
//! GRAB imload_wingdi.cpp IMPLEMENTATION 
#endif
#if OLC_IMAGELOADER == OLC_IMAGELOADER_MACOS
//! GRAB imload_macos.cpp IMPLEMENTATION 
#endif
#define PGE_IMAGELOADER_IMPLEMENTED 1
#endif

