plugins {
    id "com.android.application"
}

android {
    namespace 'com.olcpge3.android'
    compileSdkVersion 36

    defaultConfig {
        applicationId = 'com.olcpge3.android'

        minSdk 30
        targetSdk 36

        versionCode 1
        versionName '1.0'

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_static'
                cppFlags '-std=c++20'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
        }
    }

    buildFeatures {
        prefab true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles(
                    getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
            )
        }
    }
}
