name: Tests

on:
  push:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
    input:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual run'

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        echo "Placeholder for the future installation of depenedencies"

    - name: Build
      run: |
        cmake -S dev -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
        cmake --build build --config=Release

  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpng-dev \
          libgl1-mesa-dev \
          libx11-dev \
          libpthread-stubs0-dev

    - name: Build
      run: |
        cmake -S dev -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
        cmake --build build --config=Release

  mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        brew install cmake

    - name: Build
      run: |
        cmake -S dev -B build -G Xcode -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
        cmake --build build --config=Release

  emscripten:
    name: Emscripten
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python (required for Emscripten)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
        shell: bash

      - name: Build
        run: |
          source emsdk/emsdk_env.sh
          emcmake cmake -S dev -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
          cmake --build build --config=Release
        shell: bash